### ISSUE TITLE
Unhandled checks on email validator

### ISSUE THREAD

**Issue by devikasondhi** [python-validators/validators#108]
Hello,

I've come across a few checks that the current email validator does not take into account. Sharing them below.

1) Local part of the email address should be less than 64 bytes. However, the validator returns True for `john56789.john56789.john56789.john56789.john56789.john56789.john5@example.com`

2) The `name <email_id>` format isn't supported, even though it is valid as per RFC 2822 (https://tools.ietf.org/html/rfc2822#page15). Example: `Abigail <abigail@example.com>` is unexpectedly returned as invalid

3) Multiple `@` in the email aren't handled. Example of a valid email: `Abigail<@a,@b,@c:abigail@example.com>`

Thanks.

**Comment by micahcochran** [comment]
#22 has a few other examples in which the email validator could use some improvement.

**Comment by ShivaShankerReddy** [comment]
@devikasondhi i will say everything is vaid other than 2. I don't think we should email along with name?

**Comment by joe733** [comment]
[RFC 2822](https://www.rfc-editor.org/rfc/rfc2822) is obsoleted by [RFC 5322](https://www.rfc-editor.org/rfc/rfc5322)
