### ISSUE TITLE
Valid slugs

### ISSUE THREAD

**Issue by devikasondhi** [python-validators/validators#109]
Is it valid for a slug to contain upper case letters? The input `'NOT-AS-UPPERCASE'` to `slug()` is returned as a valid slug.
Also, the presence of hyphens(-)  at the beginning or end of the string isn't handled. For instance, the input `'-no-no-no-' ` to `slug()` should return `False`, while it returns a `True`.

**Comment by joe733** [comment]
Can you please elaborate? Context and conditions for a slug? reference?
