### ISSUE TITLE
Failures for email

### ISSUE THREAD

**Issue by thestick613** [python-validators/validators#115]
In [10]: validators.email('deadbeef==@yahoo.com')                                                                                                                                                           
Out[10]: True

In [11]: validators.email('%s@yahoo.com')                                                                                                                                                                   
Out[11]: True

In [12]: validators.email("deadbeef=='@yahoo.com")                                                                                                                                                          
Out[12]: True

**Comment by kvesteri** [comment]
PRs welcome

**Comment by thestick613** [comment]
Well these are in the RFC, so they are technically valid. I'm pretty sure nobody uses % or = in email addresses nowdays.

**Comment by kingbuzzman** [comment]
`pip install validate_email`

```
import validate_email
>>> validate_email.validate_email('deadbeef==@yahoo.com')
True
>>> validate_email.validate_email('%s@yahoo.com')
True
>>> validate_email.validate_email("deadbeef=='@yahoo.com")
True
```

These are all valid. This can be closed.
