### ISSUE TITLE
A valid url produces ValidationFailure

### ISSUE THREAD

**Issue by oakkitten** [python-validators/validators#116]
https://xn----8sbfxoeboc6b7i.xn--p1ai

    validators.url("https://xn----8sbfxoeboc6b7i.xn--p1ai")
    ValidationFailure(func=url, args={'value': 'https://xn----8sbfxoeboc6b7i.xn--p1ai', 'public': False})

**Comment by Marcussk** [comment]
This Issue is duplicate of #87.
