### ISSUE TITLE
Domain with colons at beginning returns True

### ISSUE THREAD

**Issue by rehmatworks** [python-validators/validators#120]
I'm using validators in an automation script where I'm creating vhosts for Apache dynamically. A validation issue broke the vhost as domain names with colons at beginning are validated as True. For example `:example.com` is validated as a valid domain but it shouldn't. Any thoughts?

**Comment by alertedsnake** [comment]
Looks like this was a bug up until 0.13.0, where it's fixed.
Which sucks, since due to #123 it means there is not a version which is not buggy.
