### ISSUE TITLE
validate if a URL is an image

### ISSUE THREAD

**Issue by jabbalaci** [python-validators/validators#13]
I have a feature request: validate a URL if it's an image or not. 

Rationale: I'm writing a scraper that extracts all links. From this list I want to filter out just the image links. I think it could be done simply by analyzing the URL string: if it contains .jpg or .png or .gif then it's an image.

**Edit:** here is my current solution

```
IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif']    # can be extended

def is_image(path):
    """
    Path can be a URL or a local file. Decide if it's an image or not.
    """
    path = path.lower()
    for x in IMAGE_EXTENSIONS:
        if x in path:
            return True
    #
    return False
```

**Comment by kvesteri** [comment]
I'm fine with adding this as long as its named a bit differently, maybe omething like ``image_url``. Also please not that your code has a bug it would return ``True`` for image url such as 'myjpg.doc'

**Comment by jabbalaci** [comment]
Let's add dot to the extensions then:

    IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif']

I've already seen URLs like this: `http://host/pic.jpg?w=20&h=20`, thus instead of `endswith` I do substring match.

Do you want a pull request?

**Comment by kvesteri** [comment]
Yeah you can create a PR but you need to do much smarter url parsing. Consider also filename urls such as: http://host/my.jpg.xlsx

Or what if the hostname contains one the image extensions? This needs to be bulletproof.

**Comment by jabbalaci** [comment]
If you want a bulletproof solution, then:

1) if it's a local file, check the header of the file (see the `file` command)
2) if it's a URL, download the header (HEAD) and check the mimetype

Both of them are slow.

**Comment by kvesteri** [comment]
That's why this should be named ``image_url`` not ``image`` if we are going to add ``image`` validator I would make it work as you suggested. ``image_url`` validator should only validate the url string using smart string parsing.

**Comment by jabbalaci** [comment]
Here is a gist of it: https://gist.github.com/jabbalaci/a1bf5cafc223ac887db0 . Maybe it would be better if you integrated it. You know better where you want it to be placed.

**Comment by shirizaan** [comment]
Thought I had it. Ran into problems. Still working on something for this.

**Comment by yozachar** [comment]
Today, URLs do not need to end in any specific extension to locate media. For example: `https://images.unsplash.com/photo-1520446266423-6daca23fe8c7`.

A plausible method to validate if the URL points to a image is to actually `GET` the content at the URL and analyse it. It think that is beyond the scope of the library, at least for now.
