### ISSUE TITLE
Valid scheme produces Validation Error

### ISSUE THREAD

**Issue by fili** [python-validators/validators#150]
e.g. 
ssh+git@github.com:kvesteri/validators.git#egg=validators
mailto:example@example.com

See also:
- https://tools.ietf.org/html/rfc3986.html#section-3.1
- https://tools.ietf.org/html/rfc3986.html#section-1.1.2
- https://tools.ietf.org/html/rfc2368.html

**Comment by kvesteri** [comment]
PRs welcome :+1:

**Comment by joe733** [comment]
related #40 #55 | ref #241
