### ISSUE TITLE
Url Validation

### ISSUE THREAD

**Issue by devikasondhi** [python-validators/validators#155]
Hello,

Here are some scenarios where ```url``` shows unexpected behaviour:
1) ```url('http://:pass@www.apache.org:80/path')``` returns ```True``` while it should throw ```ValidationFailure``` as it is invalid userinfo and password format (missing user). A valid one: ```http://user:pass@www.apache.org:80/path```
2)  no check on ports above max limit of 16-bit unsigned integer: validation ```http://example.rocks:65536/``` should fail
3) ```http://www.example.org/../world``` is invalid but ```url``` gives ```True```. ```http://www.example.org/..``` also should be invalid
4) A test from validators library, ```http://a.b--c.de/``` should be valid as per https://tools.ietf.org/html/rfc3986#page-49 but it throws ```ValidationFailure```

**Comment by kvesteri** [comment]
PRs welcome with unit test cases covering all the aforementioned scenarios

**Comment by koaning** [comment]
I've also noticed a strange instance. 

```python
import validators
# this is true
validators.url('https://player.vimeo.com/video/https://vimeo.com/439727448')
```

I'll keep the PR in mind. I'll see if I've got some time for it, I really like the idea of this package :)

**Comment by koaning** [comment]
Would we be open to checking if the URL exists? We could send a request and check if we get an appropriate status back.

**Comment by kvesteri** [comment]
> Would we be open to checking if the URL exists? We could send a request and check if we get an appropriate status back. It might make for a nice smoke test if nothing else.

> I'd add this as an optional parameter to the current url method or as a seperate function altogether. If folks think this is a good/bad idea: I'm certainly open to feedback on this one.

Personally I think this is out of scope of this library.

**Comment by koaning** [comment]
That's fair. If I figure out a neat solution to the url regex I'll report back with a PR.
