### ISSUE TITLE
incorrect URL validation

### ISSUE THREAD

**Issue by ENZ0g** [python-validators/validators#181]
url 'http://wwww.example.ex' (four letters w)  is validated as correct
```python
import validators

if validators.url('http://wwww.example.ex'):
    print('valid')
else:
    print('not valid')

# will output valid
```

**Comment by wolfgangpfnuer** [comment]
well it's a valid subdomain.
www is nothing special, just a subdomain that by convention is used a lot.

https://superuser.com/questions/144323/what-does-the-www8-or-www6-in-a-url-mean

**Comment by ENZ0g** [comment]
Thanks for the explanation! Sorry for my stupidity!
