### ISSUE TITLE
localhost and localhost. are valid domains, but give ValidationFailure

### ISSUE THREAD

**Issue by milahu** [python-validators/validators#185]
```python
import validators
validators.domain('localhost') # -> ValidationFailure
validators.domain('localhost.') # -> ValidationFailure
```
refs
* https://stackoverflow.com/questions/2532053/validate-a-hostname-string

edit: or does 'domain' mean 'fully qualified domain name'? ([fqdn](https://github.com/ypcrts/fqdn/blob/develop/fqdn/__init__.py#L65))
then 'localhost' is invalid

**Comment by stevecj** [comment]
Regardless of the intention of this method with regard to local vs Internet domains, it would be very nice to have a way to specify what is desired. Either additional validation functions or additional arguments to say whether names without any dot separators should be valid and whether IPv4 addresses should be valid and whether IPv6 addresses should be valid.

**Comment by blakev** [comment]
@stevecj makes a good point. The `url` validation function doesn't work as expected.

**Comment by joe733** [comment]
related: #142

**Comment by aaronkurz** [comment]
@yozachar So localhost is not seen as a valid domain I suppose?

**Comment by yozachar** [comment]
> @yozachar So localhost is not seen as a valid domain I suppose?

No, but a valid simple hostname.
