### ISSUE TITLE
ipfs uri validation

### ISSUE THREAD

**Issue by SlimBeji** [python-validators/validators#195]
Hello,

Thanks for this awesome library.

I just want to report a tiny issue regarding uri validation:

```
import validators
uri = "ipfs://someRandomProprietaryAACFile"
validators.url(uri)
```

The above code returns a ValidationFailure despite the fact that the uri is a valid ipfs uri.
Probably validation does not take into account the ipfs protocol.

Is it possible to add it to validators.url?

Thanks

**Comment by joe733** [comment]
related #40 #55
