### ISSUE TITLE
Does/should validators check for a static list of currently valid Top Level Domains (TLD)? 

### ISSUE THREAD

**Issue by jlegido** [python-validators/validators#198]
First of all many thanks to all the people involved in this project, I really appreciate his/her time.

I was wondering if library is expected to simply validate a domain from a RFC standpoint or is expected to check a [list of TLDs](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) for instance.

### Steps to reproduce

1. Create a script

```
cat <<EOF >> test.py
#!/usr/bin/python3
from validators import domain
print(domain("sanpellegrino-corporate.itOLDWEBSITE"))
EOF
```

2. Execute it

```
python3 test.py
```

### Expected behaviour

```
False
```

### Found behaviour

```
True
```

### Errors

None

### Additional information

Operating system:

```
Debian GNU/Linux bookworm/sid \n \l
```

Library version:

```
validators         0.18.2
```

Python version:

```
Python 3.9.9
```

**Comment by maaaaz** [comment]
I think it could be a good idea to use the daily updated list of TLD:
https://www.icann.org/resources/pages/tlds-2012-02-25-en
https://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by aviiciii** [comment]
is this implemented? if not I would ilke to work on this.

**Comment by joe733** [comment]
Sure, go ahead.
