### ISSUE TITLE
Falsely detects unicode with FULL STOP as valid domain (eg ⒈com)

### ISSUE THREAD

**Issue by IngoOutgo** [python-validators/validators#199]
The following tech spec says "all characters (other than the 4 label separators) that contained a FULL STOP in their compatibility decompositions" are forbidden. This makes sense, for example `⒈com` is definitely not a valid domain. 

![image](https://user-images.githubusercontent.com/10791710/150104964-99d23571-68f5-4184-b47c-5a6a376d42b7.png)

**Comment by joe733** [comment]
Conflicting https://github.com/python-validators/validators/issues/74
