### ISSUE TITLE
Add validation for base64/ 58, sha256

### ISSUE THREAD

**Issue by pickaxe828** [python-validators/validators#203]

**Comment by w4rc0n** [comment]
You can just use regex for these.

base64: `^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{4})$`

base58: `^5[HJK][0-9A-Za-z&&[^0OIl]]{49}$`

sha256sum: `^[A-Fa-f0-9]{64}$`

In python:
```python
import re

string = 'somestring'

if re.match('^[A-Fa-f0-9]{64}$', somestring):
    print('Match!')
else:
    print('No match!')
```

A validation library is great for things that can vary widely like domains, emails, etc. But hashes and b64/58 encoding has to follow a certain format, so regex is that way to go imo.

**Comment by Quix0r** [comment]
How about semantic version numbers?

**Comment by maaaaz** [comment]
https://github.com/python-validators/validators/issues/313
