### ISSUE TITLE
Python 3.11 wheel missing

### ISSUE THREAD

**Issue by dettmar** [python-validators/validators#253]
Hi! I recently migrated a project from Python 3.10 to 3.11 and although everything runs well, I noticed it added about a minute extra build time in my ci/cd pipeline. It seems as if validators doesn't provide a wheel for 3.11 and I was wondering if this is on the horizon?

Unfortunately I'm not experienced doing that myself, but please let me know if I can assist with anything,.

Thanks for your effort!

**Comment by joe733** [comment]
Hi @dettmar, `validators 0.20.0` officially supports these:  https://github.com/python-validators/validators/blob/9c35f185c0d44c3cb1c7433c66e3dfbb921e5e54/setup.py#L62-L64

I've made a couple of changes and now it's: https://github.com/python-validators/validators/blob/e04b4e1fc4a6e23be62a66f1b86fa1dfe7b29a44/pyproject.toml#L18-L21

Few more changes need to be made before a release.

**Comment by joe733** [comment]
If you're using an Apline based Python image for build in CI/CD pipeline, it might slow you down.

See:

- https://pythonspeed.com/articles/alpine-docker-python/
- https://github.com/docker-library/python/issues/509
- https://stackoverflow.com/questions/49037742/why-does-it-take-ages-to-install-pandas-on-alpine-linux
