### ISSUE TITLE
0.21.0: remoed sphinx suport

### ISSUE THREAD

**Issue by kloczek** [python-validators/validators#258]
Is it any reason why docsconf.py has been removed?
mkdoc does not support generate man page which swill is most common U*nix documentation format.

**Comment by joe733** [comment]
Validators is not a CLI tool (yet?), so I doubt man pages are unavoidable. On the other hand Python's [`help()`](https://docs.python.org/3/library/functions.html#help) works fine.

```py
>>> help(validators)
 
Help on package validators:

NAME
    validators - Validate Anything!

PACKAGE CONTENTS
    _extremes
    between
    btc_address
    card
    domain
    email
    hashes
    hostname
    i18n (package)
    iban
    ip_address
    length
    mac_address
    slug
    url
    utils
    uuid

CLASSES
    builtins.Exception(builtins.BaseException)
        validators.utils.ValidationFailure
    
    class ValidationFailure(builtins.Exception)

...
```

**Comment by kloczek** [comment]
> I have not qualms in adding Sphinx, except that it feels clunky and redundant.

Issue is that documentation include is packaged mdule is not only for you.

> Help me understand, how do you use man pages, of a library (a non-CLI tool)?

Man command provides acess to the DOCUMENTATION.
From man1(1):
```man
       The table below shows the section numbers of the manual followed by the types of pages they contain.

       1   Executable programs or shell commands
       2   System calls (functions provided by the kernel)
       3   Library calls (functions within program libraries)
       4   Special files (usually found in /dev)
       5   File formats and conventions, e.g. /etc/passwd
       6   Games
       7   Miscellaneous (including macro packages and conventions), e.g. man(7), groff(7), man-pages(7)
       8   System administration commands (usually only for root)
       9   Kernel routines [Non standard]

       A manual page consists of several sections.
```
On packagin modules I'm packaging python modules documentation as lvl 3 man pages and if you will look on copied generated man page for your module that man page provides exactly what shoud bi provided on that level.

Reall .. pleas restore conf,py to allow generate documentation for your module as man page.

**Comment by joe733** [comment]
> Issue is that documentation include is packaged mdule is not only for you.

Agreed, that's why I've taken extra setups to generate markdown documentation for offline package distribution. 

https://github.com/python-validators/validators/blob/68227f223d92146f87e3cd2c55e0d77564243e28/build.py#L13

https://github.com/python-validators/validators/blob/68227f223d92146f87e3cd2c55e0d77564243e28/.github/workflows/build.yml#L37-L41

> Man command provides acess to the DOCUMENTATION.

I understand what man-pages do.

> On packagin modules I'm packaging python modules documentation as lvl 3 man pages.

Can you please elaborate?

---

By the way you can still generate man-formatted documentation using [`podc3`](https://pypi.org/project/pdoc3/) and [`pandoc`](https://pandoc.org/).

``` console
$ pdoc --html --output-dir html-docs validators
$ pandoc -s -t man html-docs/validators/index.html -o validators.1
$ man ./validators.1
```

```man
validators API documentation()                                     validators API documentation()

Package validators
       Validate Anything!  Expand source code

              """Validate Anything!"""
              # -*- coding: utf-8 -*-

              # isort: skip_file

              # The following imports are sorted alphabetically, manually.
              # Each line is grouped based first or type, then sorted alphabetically.
              # This is for the reference documentation.

              # local
              from .between import between
              from .btc_address import btc_address
              from .card import amex, card_number, diners, discover, jcb, mastercard, unionpay, visa
```

**Comment by kloczek** [comment]
Thank you 👍
