### ISSUE TITLE
v0.21.0 build failed

### ISSUE THREAD

**Issue by brianeclow** [python-validators/validators#259]
The [build for v0.21.0](https://github.com/python-validators/validators/actions/runs/4530859408/jobs/7980310139) failed, which means the pypi version has not been updated.

**Comment by brianeclow** [comment]
The build is fixed, but the pypi version was not bumped to the current tag/version.

**Comment by joe733** [comment]
Waiting for a reply to https://github.com/python-validators/validators/pull/256#issuecomment-1483693548 from @kvesteri.
