### ISSUE TITLE
Publishing `v0.21.2` to PyPI

### ISSUE THREAD

**Issue by brianeclow** [python-validators/validators#268]
The [build for v0.21.1](https://github.com/python-validators/validators/actions/runs/4684567826/jobs/8300848302) failed, which means the pypi version has not been updated.

Similar to #259

**Comment by joe733** [comment]
I do not have access to publish to PyPI. See: https://github.com/python-validators/validators/pull/256#issuecomment-1483693548.

**Comment by joe733** [comment]
If you look at https://github.com/python-validators/validators/compare/0.20.0...0.20.1 and https://github.com/python-validators/validators/compare/0.20.0...0.21.1, we're dropping support for every version below `Python 3.8.0`.

![image](https://user-images.githubusercontent.com/38415384/236978969-ef8c3937-db81-483b-a1c5-d565f1b01004.png)

Now this is a huge number users on GitHub alone.  I suspect a majority of them are acquainted with `0.20.0` on PyPI (with support for as low as Python 3.4). There's is no way we can push `0.21.1`, without breaking some of their workflow.

I have a few things in mind, on how to go about addressing it, but I need to know where the author other collaborators stand.

**Comment by joe733** [comment]
If you're a new / returning `validators` user, wanting to test the latest stable version. Please install it using any of the following methods, depending upon the tool you're using:

```console
$ pip install 'git+https://github.com/python-validators/validators@latest'
$ poetry add 'git+https://github.com/python-validators/validators@latest'
$ rye add 'git+https://github.com/python-validators/validators@latest'
$ pipenv install -e 'git+https://github.com/python-validators/validators@latest'
```

Check version:

```console
$ python -c "from validators import __version__; print(__version__)"
0.21.1
```

Please leave a 👍 if latest version of `validators` is working for you.

**Comment by aviiciii** [comment]
> If you look at [0.20.0...0.20.1](https://github.com/python-validators/validators/compare/0.20.0...0.20.1) and [0.20.0...0.21.1](https://github.com/python-validators/validators/compare/0.20.0...0.21.1), we're dropping support for every version below `Python 3.8.0`.
> 
> ![image](https://user-images.githubusercontent.com/38415384/236978969-ef8c3937-db81-483b-a1c5-d565f1b01004.png)
> 
> Now this is a huge of number users on GitHub alone. I suspect a majority of them are acquainted with `0.20.0` on PyPI (with support for as low as Python 3.4). There's is no way we can push `0.21.1`, without breaking some of their workflow.
> 
Typically all dependencies update and drop the support for previous version of python and this is inevitable. Developers mostly lock their version and this might not be a big issue. These are my thoughts :)

**Comment by joe733** [comment]
cc: @kvesteri

**Comment by aqeelat** [comment]
@joe733 is there any way we can reach out to @kvesteri other than here? I suspect he gets lots of notifications and our mentions would get lost in them.

**Comment by joe733** [comment]
Published: https://pypi.org/project/validators/
