### ISSUE TITLE
'https://www.coindesk.com/learn/what-is-magic-eden-how-to-get-started-on-the-nft-marketplace/ raises an error

### ISSUE THREAD

**Issue by ankitarya1019** [python-validators/validators#292]
`import validators
url= 'https://www.coindesk.com/learn/what-is-magic-eden-how-to-get-started-on-the-nft-marketplace/'
v =validators.url(url)
print(v)`

ValidationFailure(func=url, args={'reason': "encoding with 'idna' codec failed (UnicodeError: label too long)", 'value': 'https://www.coindesk.com/learn/what-is-magic-eden-how-to-get-started-on-the-nft-marketplace/'})

The url is valid, but it runs into an encoding error.

**Comment by joe733** [comment]
Hi, please update to version `0.21.2`, these have been addressed:

```console
$ . ./.venv/bin/activate
$ python -c "from validators import __version__; print(__version__)"                 
0.21.2
$ python -c "from validators import url; print(url('https://www.coindesk.com/learn/what-is-magic-eden-how-to-get-started-on-the-nft-marketplace/'))"
true
$ python -c "from validators import url; print(url('https://docs.informatica.com/master-data-management/identity-resolution/10-1/release-guide/version-9-5-3/new-features-and-changes--9-5-3-hotfix-2-/new-features--9-5-3-hotfix-2-/company_name-field.html'))"
True
```

Docs: https://python-validators.github.io/validators/
