### ISSUE TITLE
 validators requires Python '>=3.4' but the running Python is 2.7.17

### ISSUE THREAD

**Issue by MourIdri** [python-validators/validators#302]
Ihave Python 2.7 running, trying to install the lib but fails. Any workaround ?

                  root@quickapp:/home/demouser/car_rental# pip install validators
                  Collecting validators
                    Using cached https://files.pythonhosted.org/packages/d9/1f/27dff5c1ea8f36865a179581dea4f75d1ab52cd8f32ee527a592b6558b55/validators-0.17.0.tar.gz
                  validators requires Python '>=3.4' but the running Python is 2.7.17

Documentation says : 
                    Currently validators supports python versions 2.7, 3.3, 3.4, 3.5 and PyPy.

**Comment by joe733** [comment]
@MourIdri, I suppose you're referring to this https://validators.readthedocs.io/en/latest/. I'm afraid that is quite **outdated**.

You'll find the most **updated** documentation here 👉  https://python-validators.github.io/validators/.

Besides [on PyPI](https://pypi.org/project/validators/) you can see that the latest version of `validators` requires at least Python 3.8.

![image](https://github.com/python-validators/validators/assets/38415384/35fa99d3-6e70-44b0-aabb-d83a65fa642e)
