### ISSUE TITLE
Validate hash types

### ISSUE THREAD

**Issue by maaaaz** [python-validators/validators#313]
Hello there,

It would be great to have validators of hash types, such as https://github.com/blackploit/hash-identifier/blob/master/hash-id.py

Cheers!

**Comment by yozachar** [comment]
Supersedes #203

**Comment by maaaaz** [comment]
Thanks but sorry to bother: `baseXX` are not "hashes" but "encodings":
https://github.com/python-validators/validators/blob/master/tests/test_hashes.py#L9

**Comment by yozachar** [comment]
Ah yes, my bad.
