### ISSUE TITLE
Validate IP ranges

### ISSUE THREAD

**Issue by maaaaz** [python-validators/validators#314]
Hello there,

It would be great to have a validator of IPv4 and IPv6 ranges, for instance based on the builtin module https://docs.python.org/3/library/ipaddress.html

Cheers!

**Comment by yozachar** [comment]
Already in place. Ref: https://github.com/python-validators/validators/blob/8f1159718f36cef59f4e647b03c43df52b50c2d1/src/validators/ip_address.py#L4-L11

What exactly are you proposing to implement?
