### ISSUE TITLE
url validator, exotic _wildcard_ issue

### ISSUE THREAD

**Issue by jeroengui** [python-validators/validators#315]
I use the validators library in a URL scanning project. But this URL that work in the browser doesn't get recognized as a URL (replaced the tt by xx because it's a malicious sample):

hxxps://_wildcard_.jetsett.in/wwwmicrfofst/pohwernetsharaven8726skkksusukjs9916192629900177771017000172610720027111113/

I suppose the `_wildcard_` part of the domain has something to do with it...

**Comment by yozachar** [comment]
```console
$ python -c "from validators import __version__; print(__version__)"
0.22.0

$ python -c "from validators import url; print(url('hxxps://wildcard.jetsett.in/wwwmicrfofst/pohwernetsharaven8726skkksusukjs9916192629900177771017000172610720027111113'))" 
ValidationError(func=url, args={'value': 'hxxps://wildcard.jetsett.in/wwwmicrfofst/pohwernetsharaven8726skkksusukjs9916192629900177771017000172610720027111113'})

$ python -c "from validators import url; print(url('https://wildcard.jetsett.in/wwwmicrfofst/pohwernetsharaven8726skkksusukjs9916192629900177771017000172610720027111113'))"
True
```

I do not understand, it works as expected. `hxxp` / `hxxps` is a convention, not a valid protocol.

**Comment by jeroen1243** [comment]
I get that  hxxp/hxxps is just a convention. I only wanted to raise an issue about the http version.

 The Markdown syntax in this issue removed the underscores from the url with `_wildcard_`, sorry for that.
 
 
    import validators
    print(validators.url('https://_wildcard_.jetsett.in/wwwmicrfofst/pohwernetsharaven8726skkksusukjs9916192629900177771017000172610720027111113/'))

 
When I run this I get this output:

    ValidationError(func=url, args={'value': 'https://_wildcard_.jetsett.in/wwwmicrfofst/pohwernetsharaven8726skkksusukjs9916192629900177771017000172610720027111113/'})

**Comment by yozachar** [comment]
### Note to self:

Issues

- https://github.com/python-validators/validators/issues/102
- https://github.com/python-validators/validators/issues/38
- https://github.com/python-validators/validators/issues/14
- https://github.com/python-validators/validators/issues/309

PRs

- https://github.com/python-validators/validators/pull/207
- https://github.com/python-validators/validators/pull/179

Ref:

https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it#2183140

```
According to the specifications outlined in RFC 952 and RFC 1123 (which define the rules for host names), underscores (_) 
are not allowed in host names. Host names should only consist of alphanumeric characters (letters and numbers) and 
hyphens (-).

Domain names, on the other hand, can technically include underscores, but they are not commonly used. The Internet 
Engineering Task Force (IETF) recommends avoiding the use of underscores in domain names due to potential 
interoperability issues with some older systems and applications that may not handle underscores correctly.

In practice, it's best to stick with alphanumeric characters and hyphens for both host names and domain names to ensure 
compatibility and avoid any potential issues.

~ ChatGPT
```

> Use `domain name` for public URLs and `host name` validation for non-public URLs.

**Comment by jeroengui** [comment]
I'm not sure about the standard and how more I read how more confused I get, but the thing is:

Most browsers are accepting urls with subdomains like `_wildcard_.jetsett.in` and malicious actors are using them in phishing campaigns etc.

At the moment it poses a real threat, because a lot of (antivirus)  companies use validators for urls just like this one.
The urls never get in their blocklists, exposing their users to more risk because these malicious urls work fine in their browsers.

I don't know if this is something that should be fixed in the browsers, in the standard or in the validators, and the issue is definitely bigger than just this implementation. 

So to be clear:

We are figuring out if   `http://_wildcard_.domain.com` is a valid url.

We agree that `http://_wildcard.jetsett.in` and `https://my_sarisari_store.typepad.com/` are valid urls. 

So an underscore can be used in any place of the subdomain except the one right before the dot?

**Comment by jeroengui** [comment]
Some more information: It seems like SSL certificates cannot be generated for ` _wildcard_.domain.com` but a wildcard certificate like `*.domain.com` works just fine for  ` _wildcard_.domain.com`

**Comment by yozachar** [comment]
- [`rfc_1034`](https://www.rfc-editor.org/rfc/rfc1034) does not mention anything about underscore.
- [`rfc_2782`](https://www.rfc-editor.org/rfc/rfc2782) talks about prepending underscores.

> So appending underscore to sub/domain name is not encouraged, but it is technically valid.

This patch

```diff
- + r"(?:[a-zA-Z0-9-_]{0,61}[A-Za-z0-9])?\.)"
+ + rf"(?:[a-zA-Z0-9-_]{{0,61}}[A-Za-z0-9{'_'if rfc_2782 else ''}])?\.)"
```

in https://github.com/python-validators/validators/blob/854375f611ee1600727c0f4ff0778e1a3e3c7b74/src/validators/domain.py#L45

will work.

You'll have to add  `("example_.com", False, True)` to pytest parameter list of `test_returns_true_on_valid_domain()`  in `test_domain.py`.

PR is welcome.
