### ISSUE TITLE
MYPY: "validators": module is installed, but missing library stubs or py.typed marker 

### ISSUE THREAD

**Issue by tofetpuzo** [python-validators/validators#326]
Hey I am using mypy which checks the src, however, I am getting this error.
"validators": module is installed, but missing library stubs or py.typed marker 
[import-untyped]
    import validators
    ^

Ref : [missing py.typed](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker)

Is it a feature you hope to implement?

**Comment by yozachar** [comment]
`py.typed` is already present https://github.com/python-validators/validators/blob/master/src/validators/py.typed, unfortunately it was not included in the last release. I'll fix it in the next release.

**Comment by yozachar** [comment]
Completed in  #333.
