### ISSUE TITLE
What happened to ipv4_cidr() ?

### ISSUE THREAD

**Issue by tristanlatr** [python-validators/validators#328]
Hello, I'm running into error:

```
 AttributeError: module 'validators' has no attribute 'ipv4_cidr'
```

This validator have been remove on purpose ?
 And exactly at what version (nothing mentioned in the changelog) ?

Thanks

**Comment by yozachar** [comment]
Please refer: https://github.com/python-validators/validators/issues/287#issuecomment-1678325599

> And exactly at what version (nothing mentioned in the changelog) ?

Apologies, I'm working on to rectify it.
