### ISSUE TITLE
Domains with underscores fail domain() check?

### ISSUE THREAD

**Issue by Quix0r** [python-validators/validators#364]
I have found this domain: `tfirefish_01.blueb.me` and it fails:
```python
from validators import domain

print(domain('google.com'))
print(domain('tfirefish_01.blueb.me'))
```
Expected:
```
True
True
```
Current:
```
True
ValidationError(func=domain, args={'value': 'tfirefish_01.blueb.me'})
```
Python: `3.11.2`
Validators: `0.28.0`

**Comment by yozachar** [comment]
Please refer the [documentation](https://yozachar.github.io/pyvalidators/stable/api/domain/). Use `rfc_2782=True`:

```
validators.domain("tfirefish_01.blueb.me", rfc_2782=True)
```

**Comment by Quix0r** [comment]
Which one do I have to set? I checked the code and found no appearance?
