### ISSUE TITLE
Domain validator allows invalid characters in some cases

### ISSUE THREAD

**Issue by hagenrd** [python-validators/validators#366]
It appears that, currently, any character is valid for the final character in the gTLD if `rfc1034` is `True`, for example:
```
>>> domain('example.com?', rfc_1034=True, rfc_2782=False)
True
>>> domain('example.com!', rfc_1034=True, rfc_2782=False)
True
```

I believe the '.' just needs to be escaped in the pattern string ([link](https://github.com/python-validators/validators/blob/master/src/validators/domain.py#L72)):
```
+ rf"[a-z]{r'.?$' if rfc_1034 else r'$'}",
             ^
```

Also, it appears question marks are allowed when `rfc_2782` is `True` for domain validation:
```
>>> from validators import domain
>>> domain('example?.com', rfc_1034=False, rfc_2782=True)
True
```
This appears to be from the use of '?' after the '_' inside of a character class:
```
rf"^(?:[a-z0-9{r'_?'if rfc_2782 else ''}]"
                  ^
```
Presumably, this is to make the '_' optional, but since metacharacters aren't active in character classes ([link](https://docs.python.org/3/howto/regex.html#:~:text=a%2Dz%5D.-,Metacharacters,-(except%20%5C)%20are)), this is interpreted as a literal '?' instead.

**Comment by yozachar** [comment]
Hey @hagenrd thanks! Do you mind reviewing: #367

**Comment by hagenrd** [comment]
Thanks for the quick turnaround!  Any chance you have some time to provide a patch that includes those changes?

**Comment by yozachar** [comment]
https://patch-diff.githubusercontent.com/raw/python-validators/validators/pull/367.patch ?

**Comment by hagenrd** [comment]
Sorry, I meant patch in terms of a semantic version, i.e. a patch-release (0.28.1).
