### ISSUE TITLE
url validator rejects some local URLs as invalid even though they should be valid

### ISSUE THREAD

**Issue by MidnightStallion** [python-validators/validators#392]
To the best of my knowledge, a URL such as 'http://localhost' should be valid. but validators says it is not.

http://127.0.0.1 works, but http://locahost does not.

If my understanding is correct, a local host running web server does not need an FQDN for it to work. So I believe 'http://localhost' or 'http://localhost:8000' should be a valid URL.

Steps to reproduce:

1. validators.url('http://127.0.0.1')
2. Returns True
3. validators.url('http://localhost')
4. Returns a ValidationError

**Comment by yozachar** [comment]
Hi @MidnightStallion, there is a `simple_host` parameter for the `url` function.

```console
$ python -c "from validators import url; print(url('https://localhost', simple_host=True))"
True
```

I guess an example in the [documentation](https://yozachar.github.io/pyvalidators/stable/api/url/) might help.

---

ref https://github.com/python-validators/validators/issues/285#issuecomment-1676336214

**Comment by MidnightStallion** [comment]
Hi yozachar. Thanks for your fast response and sorry for the trouble. It works the way I intend when I use simple_host. Thanks for all your work on this. It has saved me a lot of time when it comes to validation.

**Comment by zx80** [comment]
My 0,02€: ISTM that `localhost` should be accepted as a special case even without the `simple_host` option.
The option basically accepts `http://anything/`, and I do not think that `localhost` is _anything_ as such.

**Comment by zx80** [comment]
> > My 0,02€: ISTM that `localhost` should be accepted as a special case even without the `simple_host` option.
> > The option basically accepts `http://anything/`, and I do not think that `localhost` is _anything_ as such.
> 
> In `/etc/hosts` you could map `127.0.0.x` to _anything_, which then becomes your _localhost_.

Sure. That is _not_ my point. My point is that `localhost` is common enough a name to appear in legitimate URLs and should be allowed without to having to trigger the `simple_host` setting which validates _any_ random one-word value.
