### ISSUE TITLE
.onion TLD

### ISSUE THREAD

**Issue by davidt99** [python-validators/validators#401]
When validating URLs with TLD enabled, `.onion` comes up as not validated. Since `.onion` URLs (TOR) are kinda unique, I wonder if we should add it to the TLD list or add a separate flag.
I can open a PR for both solutions, I just wonder what the best way is.
For context, [tldextract](https://github.com/john-kurkowski/tldextract) accepts `.onion`.

**Comment by yozachar** [comment]
Hi @davidt99, are onion URLs validated by this library? Can you show me an example? AFAIK they are not in tests.

**Comment by davidt99** [comment]
It's not validated when the `consider_tld` flag is on since `.onion` is not in the TLD list.

**Comment by yozachar** [comment]
Okay, instead of adding it to `_tld.txt`, we could append it to `_popular_cache` in [`domain.py`](https://github.com/python-validators/validators/blob/master/src/validators/domain.py#L18).

```py
_popular_cache = {"COM", "ORG", "RU", "DE", "NET", "BR", "UK", "JP", "FR", "IT"}
_popular_cache.add("ONION")
```
