### ISSUE TITLE
Bitcoin Testnet Address

### ISSUE THREAD

**Issue by bert2002** [python-validators/validators#404]
Hi,
I noticed that bitcoin testnet addresses (e.g. `tb1qlw09ycnp3qgqw9alqgx93ed7cg5kmnyud326ky`) does not pass the check. Is there a plan to add them as well?

Thanks,
bert

**Comment by yozachar** [comment]
@msamsami can I assign you this?

**Comment by msamsami** [comment]
We may not want to include support for testnet addresses. Even if we decide to, we should make sure that they are handled by separate validators to avoid conflicts with mainnet addresses.

**Comment by msamsami** [comment]
@yozachar 
I guess we can close this one as @bert2002 seems to agree with my earlier comment.

**Comment by bert2002** [comment]
> @yozachar I guess we can close this one as @bert2002 seems to agree with my earlier comment.

I thought more like `btc_testnet_address` to not break the `btc_address`.

**Comment by yozachar** [comment]
@msamsami you wanna take this up?
