### ISSUE TITLE
validator fails with url containing double hyphens for 

### ISSUE THREAD

**Issue by steelliberty** [python-validators/validators#41]
validator 11.1 fails validating a URL with double hyphens for example 

http://my--domain.com fails .. However there are many sites using double dashes in their domain name .. 

Thanks for the python module -- I use it regularly.

**Comment by akshaypinto** [comment]
Facing the same issue. Double hyphens is still a valid url except in the 3rd and 4th position
https://tools.ietf.org/html/rfc5891#section-4.2.3.1

**Comment by ramiroestrada** [comment]
Verified still an issue.  Is anyone reviewing these issues anymore? @kvesteri

**Comment by kvesteri** [comment]
PRs welcome :+1:
