### ISSUE TITLE
url without http

### ISSUE THREAD

**Issue by georgkrause** [python-validators/validators#48]
would be nice if there would be an option to validate a url without http(s) at the beginning

**Comment by rduplain** [comment]
That would make a useful option. Without it, you could use urllib from the standard library to drop the scheme from the given URL (`urlunparse(('',) + urlparse(url)[1:]).lstrip('/')`). As a utility function:

```python
# Python 3.x

from urllib.parse import urlparse, urlunparse


def drop_scheme(url):
    """Return URL string without scheme (e.g. 'http://').

    Example:

    >>> drop_scheme('http://www.example.org')
    'www.example.org'
    >>> drop_scheme('ftp://www.example.org')
    'www.example.org'
    >>> drop_scheme('example.org')
    'example.org'
    >>> drop_scheme('http://www.example.org/~username/index.html')
    'www.example.org/~username/index.html'
    >>>
    """
    parsed = urlparse(url)
    return urlunparse(('',) + parsed[1:]).lstrip('/')


if __name__ == '__main__':
    import doctest
    doctest.testmod()
```

You could then use this approach:

```
>>> validators.url('http://' + drop_scheme(url))
True
>>>
```

**Comment by georgkrause** [comment]
well, i already have a workaround for this, maybe yours is even better. anyway, implementing this would be nice!

**Comment by joe733** [comment]
I'm sorry but a URL must begin with a scheme. Ref [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986.html).
