### ISSUE TITLE
URL validation arbitrarily supports FTP, but not other protocols

### ISSUE THREAD

**Issue by nicbou** [python-validators/validators#55]
A URL can have any of an arbitrary number of protocols, but only HTTP, HTTPS and FTP are supported. If we have to arbitrarily restrict which protocols are allowed, we should at least follow the principle of least surprise and only allow HTTP(S). FTP is a weird addition.

Alternatively, supported protocols could be supplied.

**Comment by kvesteri** [comment]
Fully agree on all your points. The best way would be if user could set which schemes are allowed.

**Comment by sireliah** [comment]
Hi! I second that. The list of possibly useful schemes is provided by IANA: https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

I think we can safely skip the historical ones, however some are nice-to-haves:
```
rsync://
rmi://
redis://
mongodb://
sftp://
```
etc.

Let's discuss if this is feasible to include larger amount of schemes from document I posted.

**Comment by joe733** [comment]
related #40 #55
