### ISSUE TITLE
Why msn.comm validates?

### ISSUE THREAD

**Issue by lameei** [python-validators/validators#67]
I have the following code:
```
import validators

url = 'msn.comm'

if (validators.domain(url)) or (validators.url(url)):
    print("VALIDATION PASSED")
else:
    print("Please insert a domain name in this format: example.com")
```
And the `msn.comm` validates. Why is that?

**Comment by jbnance** [comment]
The validator merely checks that the subject is a valid domain syntactically - it does not have a list of valid TLDs nor does it attempt to resolve the domain.  Syntactically 'msn.comm' is valid (as is 'fdsfds.fsaf.asfdsa.fdsa.fsdfsa.fsadfsa', for example).

**Comment by lameei** [comment]
This is weird. So what is the propose of validation here?

**Comment by jbnance** [comment]
It is validating the format just as many validators do (the email validator doesn't send an email to make sure the account exists).  I would agree that it would be nice to have it check against a list of TLDs.  Perhaps the maintainer could pull from here regularly:

https://data.iana.org/TLD/tlds-alpha-by-domain.txt
