### ISSUE TITLE
ValidationFailure on real domains with accent characters

### ISSUE THREAD

**Issue by serain** [python-validators/validators#74]
I have a know legit domain that contains the German accent `ä`. This domain is registered, public whois record etc.

Running it through `validators.domain(target)` returns a `ValidationError`.

Apparently such domains are valid since 2003: https://www.iis.se/english/domains/se/idn/

**Comment by kvesteri** [comment]
PRs welcome!

**Comment by sheeplepie** [comment]
I'll give it a try, time to play regex gold I guess. I noticed it also trips up on valid Chinese domain names. In Latin charsets these are basically domain names and TLDs that start with `xn--`.

**Comment by stitch** [comment]
Domains like аренда.орг and मुम्बई.संगठन are valid. (disclaimer, i have not looked up the translations of these words, they might be something horrible :))

Here you'll find some more nice tld's: https://namestat.org/xn--i1b6b1a6a2e
