### ISSUE TITLE
Valid domain name taken as invalid

### ISSUE THREAD

**Issue by kdeltared** [python-validators/validators#81]
The following domain name is valid but validators take it as invalid

```
>>> validators.domain("0-1-0-0-1-0-0-0-1-0-1-1-0-1-1-1-1-0-1-1-1-0-0-0-1-1-1-1-1-1-1-.0-0-0-0-0-0-0-0-0-0-0-0-0-60-0-0-0-0-0-0-0-0-0-0-0-0-0.info")
ValidationFailure(func=domain, args={'value': '0-1-0-0-1-0-0-0-1-0-1-1-0-1-1-1-1-0-1-1-1-0-0-0-1-1-1-1-1-1-1-.0-0-0-0-0-0-0-0-0-0-0-0-0-60-0-0-0-0-0-0-0-0-0-0-0-0-0.info'})
````

![image](https://user-images.githubusercontent.com/14323062/38516839-82898ca6-3c0e-11e8-9dc3-efb230605ff9.png)

![image](https://user-images.githubusercontent.com/14323062/38517061-29013296-3c0f-11e8-89e6-826be245f748.png)

**Comment by joe733** [comment]
It seems the domain is no longer valid: https://mxtoolbox.com/SuperTool.aspx?action=mx%3a0-1-0-0-1-0-0-0-1-0-1-1-0-1-1-1-1-0-1-1-1-0-0-0-1-1-1-1-1-1-1-.0-0-0-0-0-0-0-0-0-0-0-0-0-60-0-0-0-0-0-0-0-0-0-0-0-0-0.info&run=toolpage
